import type { Metadata } from 'next'
import { EB_Garamond } from 'next/font/google'
import './globals.css'

const garamond = EB_Garamond({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BookStoreApp with Google Books | Fatmanur Guzel',
  description: 'Generated by create bookstore app',
  icons: '/favicon.ico'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={garamond.className}>
      <body className={garamond.className}>
        {children}
      </body>
    </html>
  )
}
